name = "Aethernauts"
author = "ariklego"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e48d9e4d88b2381779bd62e048bbe8d2f4c9ba97d5af833cd33badc74073b01c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
