name = "Aethernauts"
author = "ariklego"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5650d5fbf2622476d93aee2ec5c554da1c336576117ab3fe3af940824a55ee08"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
