name = "Aethernauts"
author = "ariklego"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f10e540ad4867b607edb30319b5a32eb05c45a895064013975c6a0857dd045f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
